//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DristLauncher4 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class IPCONFIGs : global::System.Configuration.ApplicationSettingsBase {
        
        private static IPCONFIGs defaultInstance = ((IPCONFIGs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IPCONFIGs())));
        
        public static IPCONFIGs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/Sesdear/ips_for_dl4/main/server_ips.json")]
        public string url_to_build {
            get {
                return ((string)(this["url_to_build"]));
            }
            set {
                this["url_to_build"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string file_server_url {
            get {
                return ((string)(this["file_server_url"]));
            }
            set {
                this["file_server_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string servers_info_url {
            get {
                return ((string)(this["servers_info_url"]));
            }
            set {
                this["servers_info_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string manifest_server_url {
            get {
                return ((string)(this["manifest_server_url"]));
            }
            set {
                this["manifest_server_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string manifest_file_name {
            get {
                return ((string)(this["manifest_file_name"]));
            }
            set {
                this["manifest_file_name"] = value;
            }
        }
    }
}
